// lib
import type { Metadata } from "next";

// components
import AppMenuBar from "@/components/custom/AppMenuBar";

export const metadata: Metadata = {
  title: "VilChain",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppMenuBar />
        {children}
      </body>
    </html>
  );
}
