// lib
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "VilChain Docs",
  description: "Generated by create next app",
  keywords: [],
};

export default function DocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
