// lib
import type { Metadata } from "next";

// layout components
import AppMenuBar from "@/components/layout/AppMenuBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function WebsiteLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <AppMenuBar />
        {children}
      </body>
    </html>
  );
}
